### ISSUE TITLE
Update : Add `--privileged` flag to docker command

### ISSUE THREAD

**Issue by Prashant-Jagtap** [imsudiproy/auditScript#9]
Add `--privileged` flag to docker command when creating the container, as some jobs/distros might require these privileges.
Thanks

**Comment by imsudiproy** [comment]
@Prashant-Jagtap added --privileged flag
https://github.com/imsudiproy/auditScript/pull/11

**Comment by Prashant-Jagtap** [comment]
Cool. Closing this issue.
